C#_Web/ASP.NET_Advanced_October_2022/SchoolMealsOrderingSystem/SchoolMealsOrderingSystem/Controllers/DailyMenuController.cs
namespace SchoolMealsOrderingSystem.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SchoolMealsOrderingSystem.Core.Contracts;
    using SchoolMealsOrderingSystem.Core.Models.Meal;
    using SchoolMealsOrderingSystem.Core.Models.DailyMenu;
    using static Data.Constants.RoleConstants;


    [Authorize]
    public class DailyMenuController : Controller
    {
        private readonly IDailyMenuServices menuServices;
        private readonly IChildServices childServices;

        public DailyMenuController(IDailyMenuServices _menuServices, IChildServices _childServices)
        {
            menuServices = _menuServices;
            childServices = _childServices;
        }


        [HttpGet]
        [Authorize(Roles = Parent)]
        public async Task<IActionResult> GetMealsForParentsToChoose(Guid childId)
        {

            var model = new MealsForParentToChooseViewModel();

            try
            {
                model = await menuServices.GetMealsForParentsToChoose(childId);
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError(string.Empty, ae.Message);
                RedirectToAction(nameof(ChildController.All));
            }

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = Parent)]
        public async Task<IActionResult> GetMealsForParentsToChoose(MealsForParentToChooseViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await menuServices.AddDailyMenuAsync(model);

                return RedirectToAction(nameof(All), new { childId = model.ChildId});
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);

                //return RedirectToAction("Error", "Home");

                return View(model);
            }


        }

        [HttpGet]
        [Authorize(Roles = SchoolAndParent)]
        public async Task<IActionResult> All(Guid childId)
        {

            var model = new MultipleDailyMenuViewModel();
            
            var menues = await menuServices.GetAllDailyMenusAsync(childId);
            var child = await childServices.GetChildByIdAsync(childId);

            model.DailyMenus = menues;
            model.ChildViewModel = child;

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = Parent)]
        public async Task<IActionResult> Delete(Guid id)
        {

            await menuServices.DeleteDailyMenuAsync(id);

            return RedirectToAction("All", "Child");


        }
    }
}

C#_Web/ASP.NET_Advanced_October_2022/SchoolMealsOrderingSystem/SchoolMealsOrderingSystem/Controllers/MealController.cs
namespace SchoolMealsOrderingSystem.Controllers
{
    using DocumentFormat.OpenXml.Office2013.Drawing.ChartStyle;
    using DocumentFormat.OpenXml.Spreadsheet;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SchoolMealsOrderingSystem.Core.Contracts;
    using SchoolMealsOrderingSystem.Core.Models.Child;
    using SchoolMealsOrderingSystem.Core.Models.Meal;
    using SchoolMealsOrderingSystem.Core.Services;
    using System.Security.Claims;
    using static Data.Constants.RoleConstants;
    using static Data.Constants.SchoolUserConstants;
    using static Data.Constants.SoupConstants;
    using static Data.Constants.MainDishConstants;
    using static Data.Constants.DessertConstatnts;

    [Authorize]
    public class MealController : Controller
    {
        private readonly IMealServices mealServices;

        public MealController(IMealServices _mealServices)
        {
            mealServices = _mealServices;
        }

        [HttpGet]
        [Authorize(Roles = School)]
        public IActionResult AddSoup()
        {

            var model = new AddSoupViewModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = School)]
        public async Task<IActionResult> AddSoup(AddSoupViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            string schoolUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            try
            {


                await mealServices.AddSoupAsync(model, schoolUserId);


                return RedirectToAction(nameof(AllSoups));

            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, InvalidSchoolUserId);

                return View(model);
            }
        }

        [HttpGet]
        [Authorize(Roles = School)]
        public IActionResult AddMainDish()
        {

            var model = new AddMainDishViewModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = School)]
        public async Task<IActionResult> AddMainDish(AddMainDishViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            string schoolUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            try
            {


                await mealServices.AddMainDishAsync(model, schoolUserId);


                return RedirectToAction(nameof(AllMainDishes));

            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, InvalidSchoolUserId);

                return View(model);
            }
        }

        [HttpGet]
        [Authorize(Roles = School)]
        public IActionResult AddDessert()
        {

            var model = new AddDessertViewModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = School)]
        public async Task<IActionResult> AddDessert(AddDessertViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            string schoolUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            try
            {


                await mealServices.AddDessertAsync(model, schoolUserId);


                return RedirectToAction(nameof(AllDesserts));

            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, InvalidSchoolUserId);

                return View(model);
            }
        }


        [HttpGet]
        [Authorize(Roles = School)]
        public async Task<IActionResult> AddMealsToSchoolList()
        {

            string schoolUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var model = new AddMealsToSchoolListViewModel
            {
                Soups = await mealServices.GetSoupsAsync(schoolUserId),
                MainDishes = await mealServices.GetMainDishsAsync(schoolUserId),
                Desserts = await mealServices.GetDessertsAsync(schoolUserId)
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = School)]
        public async Task<IActionResult> AddMealsToSchoolList(AddMealsToSchoolListViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }


            try
            {

                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);


                await mealServices.AddMealsAsync(model, userId);


                return RedirectToAction("Index", "Home", new { area = SchoolAreaName });

            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, InvalidSchoolUserId);

                return View(model);
            }
        }

        [HttpGet]
        [Authorize(Roles = SchoolAndParent)]
        public async Task<IActionResult> AllSoups(string schoolId)
        {



            IEnumerable<SoupViewModel> model;

            if (schoolId != null)
            {
                model = await mealServices.GetSoupViewModelAsync(schoolId);
            }
            else
            {
                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                model = await mealServices.GetSoupViewModelAsync(userId);
            }


            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = SchoolAndParent)]
        public async Task<IActionResult> AllMainDishes(string schoolId)
        {

            IEnumerable<MainDishViewModel> model;

            
            if (schoolId != null)
            {
                model = await mealServices.GetMainDishViewModelAsync(schoolId);
            }
            else
            {
                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                model = await mealServices.GetMainDishViewModelAsync(userId);
            }


            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = SchoolAndParent)]
        public async Task<IActionResult> AllDesserts(string schoolId)
        {

            
            IEnumerable<DessertViewModel> model;


            if (schoolId != null)
            {
                model = await mealServices.GetDessertViewModelAsync(schoolId);
            }
            else
            {
                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                model = await mealServices.GetDessertViewModelAsync(userId);
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = School)]
        public async Task<IActionResult> EditSoup(Guid soupId)
        {

            var soup = await mealServices.GetSoupForEditAsync(soupId);

            if (soup == null)
            {
                return RedirectToAction(nameof(AllSoups));
            }

            return View(soup);
        }


        [HttpPost]
        [Authorize(Roles = School)]
        public async Task<IActionResult> EditSoup(EditSoupViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {

                await mealServices.EditSoupAsync(model);


                return RedirectToAction(nameof(AllSoups));

            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, InvalidSoupId);

                return View(model);
            }
        }

        [HttpGet]
        [Authorize(Roles = School)]
        public async Task<IActionResult> EditMainDish(Guid mainDishId)
        {

            var mainDish = await mealServices.GetMainDishForEditAsync(mainDishId);

            if (mainDish == null)
            {
                return RedirectToAction(nameof(AllMainDishes));
            }

            return View(mainDish);
        }


        [HttpPost]
        [Authorize(Roles = School)]
        public async Task<IActionResult> EditMainDish(EditMainDishViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {

                await mealServices.EditMainDishAsync(model);


                return RedirectToAction(nameof(AllMainDishes));

            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, InvalidMainDishId);

                return View(model);
            }
        }

        [HttpGet]
        [Authorize(Roles = School)]
        public async Task<IActionResult> EditDessert(Guid dessertId)
        {

            var dessert = await mealServices.GetDessertForEditAsync(dessertId);

            if (dessert == null)
            {
                return RedirectToAction(nameof(AllDesserts));
            }

            return View(dessert);
        }


        [HttpPost]
        [Authorize(Roles = School)]
        public async Task<IActionResult> EditDessert(EditDessertViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {

                await mealServices.EditDessertAsync(model);


                return RedirectToAction(nameof(AllDesserts));

            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, InvalidDessertId);

                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSoup(Guid soupId)
        {

            await mealServices.DeleteSoupAsync(soupId);

            return RedirectToAction(nameof(AllSoups));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMainDish(Guid mainDishId)
        {

C#_Web/ASP.NET_Advanced_October_2022/SchoolMealsOrderingSystem/SchoolMealsOrderingSystem/Views/DailyMenu/All.cshtml
@model MultipleDailyMenuViewModel

@{
    ViewBag.Title = @Localizer[LayoutTitleName];
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="parent">
    <div class="child text-center row">
        <div class="card col-4" style="width: 20rem; margin-right: 7px; margin-bottom: 7px; background-color: honeydew">
            <div class="image-content" style="padding: 15px">
                <div class="card-image">
                    <img src="@Model.ChildViewModel.ImageUrl" alt="" class="avoid-clicks card-img" style="padding: 2px">
                </div>
            </div>
            <div class="card-body" style="padding: 10px">

                <h5 class="card-title mt-1" style="color: darkgreen">@Model.ChildViewModel.FirstName @Model.ChildViewModel.LastName</h5>
                @if (@Model.ChildViewModel.MonthsOld != 0)
                {
                    <p class="mb-2" style="color: darkviolet">@Localizer[Age]: @Model.ChildViewModel.YearsOld @Localizer[YearsOfTheChild] @Localizer[And] @Model.ChildViewModel.MonthsOld @Localizer[MonthsOfTheChild]</p>
                }
                else
                {
                    <p class="mb-2" style="color: darkviolet">@Localizer[Age]: @Model.ChildViewModel.YearsOld @Localizer[YearsOfTheChild]</p>
                }
                <p class="mb-0" style="color: coral">@Localizer[SchoolName]: @Model.ChildViewModel.School</p>
                <p class="mb-0" style="color: darkblue">@Localizer[YearInSchool]: @Model.ChildViewModel.YearInSchool</p>
            </div>
            @if (User.IsInRole(Parent))
            {
                <div class="mb-3">
                    <a asp-controller="DailyMenu" asp-action="GetMealsForParentsToChoose" asp-route-childId="@Model.ChildViewModel.Id" class="fs-6 btn btn-outline-success mb-3 p-2">@Localizer[ChooseMenu]</a>
                </div>
            }
        </div>
    </div>

    <div class="child text-center row">
        @if (!Model.DailyMenus.Any())
        {
            <h3>@Localizer[NoSelectedMenusYet]</h3>
        }
        else
        {
            @foreach (var dailyMenu in Model.DailyMenus)
            {
                <div class="card col-4" style="width: 20rem; margin-right: 7px; margin-bottom: 7px; background-color: honeydew">
                    <div class="card-body">
                        @if (dailyMenu.Name.Equals(DayOfWeek.Monday.ToString()))
                        {
                            <h5 class="card-title mt-1" style="color: darkgreen">@Localizer[Monday]</h5>
                        }
                        else if (dailyMenu.Name.Equals(DayOfWeek.Tuesday.ToString()))
                        {
                            <h5 class="card-title mt-1" style="color: darkgreen">@Localizer[Tuesday]</h5>
                        }
                        else if (dailyMenu.Name.Equals(DayOfWeek.Wednesday.ToString()))
                        {
                            <h5 class="card-title mt-1" style="color: darkgreen">@Localizer[Wednesday]</h5>
                        }
                        else if (dailyMenu.Name.Equals(DayOfWeek.Thursday.ToString()))
                        {
                            <h5 class="card-title mt-1" style="color: darkgreen">@Localizer[Thursday]</h5>
                        }
                        else if (dailyMenu.Name.Equals(DayOfWeek.Friday.ToString()))
                        {
                            <h5 class="card-title mt-1" style="color: darkgreen">@Localizer[Friday]</h5>
                        }
                        <p class="mb-0" style="text-align: left">@Localizer[SoupString]: @dailyMenu.Soup.Name</p>
                        <p class="mb-0" style="text-align: left">@Localizer[MainDishString]: @dailyMenu.MainDish!.Name</p>
                        <p class="mb-0" style="text-align: left">@Localizer[DessertString]: @dailyMenu.Dessert!.Name</p>
                    </div>
                    @if (User.IsInRole(Parent))
                    {
                        <form asp-controller="DailyMenu" asp-action="Delete" asp-route-id="@dailyMenu.Id">
                            <div>
                                <input style="margin-bottom: 10px" type="submit" onclick="myConfirm(event)" value="@Localizer[Delete]" class="btn btn-outline-danger" />
                            </div>
                        </form>
                    }

                </div>
            }
        }
    </div>
</div>

@section Scripts {
    <partial name="_DeleteScriptPartial" />
    <partial name="_RemoveContainerClassDivPartial" />
    <script>
        let footer = document.querySelector('footer');

        let shouldRemoveFooter = true; 

        if (shouldRemoveFooter) {
            footer.style.display = 'none';
        }
    </script>
}

C#_Web/ASP.NET_Advanced_October_2022/SchoolMealsOrderingSystem/SchoolMealsOrderingSystem/Views/DailyMenu/GetMealsForParentsToChoose.cshtml
@model MealsForParentToChooseViewModel

@{
    ViewBag.Title = Localizer[LayoutTitleName];
}


<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-controller="DailyMenu" asp-action="GetMealsForParentsToChoose" asp-route-childId="@Model.ChildId" method="post">
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.SchoolId" />
            <div class="mb-3">
                <label asp-for="@Model.DayOfTheWeek" class="form-label">@Localizer[Day]</label>
                <select asp-for="@Model.DayOfTheWeek" class="form-control">
                    <option value="">-- @Localizer[ChooseTheDayOfTheMenu] --</option>
                    @if (!Model.DailyMenus.Any(x => x.Name.Equals(DayOfWeek.Monday)))
                    {
                        <option value="@DayOfWeek.Monday">@Localizer[Monday]</option>
                    }
                    @if (!Model.DailyMenus.Any(x => x.Name.Equals(DayOfWeek.Tuesday)))
                    {
                        <option value="@DayOfWeek.Tuesday">@Localizer[Tuesday]</option>
                    }
                    @if (!Model.DailyMenus.Any(x => x.Name.Equals(DayOfWeek.Wednesday)))
                    {
                        <option value="@DayOfWeek.Wednesday">@Localizer[Wednesday]</option>
                    }
                    @if (!Model.DailyMenus.Any(x => x.Name.Equals(DayOfWeek.Thursday)))
                    {
                        <option value="@DayOfWeek.Thursday">@Localizer[Thursday]</option>
                    }
                    @if (!Model.DailyMenus.Any(x => x.Name.Equals(DayOfWeek.Friday)))
                    {
                        <option value="@DayOfWeek.Friday">@Localizer[Friday]</option>
                    }
                    @if (Model.DailyMenus.Count() == 5)
                    {
                        <option value="">@Localizer[YouHaveChosenAMenuForEveryDay]</option>
                    }
                </select>
                <span asp-validation-for="DayOfTheWeek" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.SoupId" class="form-label">@Localizer[ChooseSoup]</label>
                <select asp-for="@Model.SoupId" class="form-control">
                    <option value="">-- @Localizer[ChooseSoup] --</option>
                    @foreach (Soup soup in Model.Soups)
                    {
                        <option value="@soup.Id">@soup.Name</option>
                    }
                </select>
                <span asp-validation-for="SoupId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.MainDishId" class="form-label">@Localizer[ChooseAMainDish]</label>
                <select asp-for="@Model.MainDishId" class="form-control">
                    <option value="">-- @Localizer[ChooseAMainDish] --</option>
                    @foreach (MainDish mainDish in Model.MainDishes)
                    {
                        <option value="@mainDish.Id">@mainDish.Name</option>
                    }
                </select>
                <span asp-validation-for="MainDishId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.DessertsId" class="form-label">@Localizer[ChooseADessert]</label>
                <select asp-for="@Model.DessertsId" class="form-control">
                    <option value="">-- @Localizer[ChooseADessert] --</option>
                    @foreach (Dessert dessert in Model.Desserts)
                    {
                        <option value="@dessert.Id">@dessert.Name</option>
                    }
                </select>
                <span asp-validation-for="DessertsId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-outline-primary" type="submit" value="@Localizer[Add]" />
            </div>
        </form>
        <div class="mb-3">
            <a class="btn btn-outline-success" asp-area="" asp-controller="Meal" asp-action="AllSoups" asp-route-schoolId="@Model.SchoolId">@Localizer[SeeSoups]</a>
            <a class="btn btn-outline-warning" asp-area="" asp-controller="Meal" asp-action="AllMainDishes" asp-route-schoolId="@Model.SchoolId">@Localizer[SeeMainDishes]</a>
            <a class="btn btn-outline-primary" style="background-color: #F0DB35" asp-area="" asp-controller="Meal" asp-action="AllDesserts" asp-route-schoolId="@Model.SchoolId">@Localizer[SeeDesserts]</a>
        </div>
    </div>

</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}